/*
    Variáveis
    - let ---> LET VOCÊ PODE IR TROCANDO O VALOR 
    - cont ---> VALOR NÃO PODE SER DECLARO NOVAMENTE 
    - var ---> DESCONTINUADO / NÃO USAR
    - OBS ----> QUANDO FOR PROCURAR UMA VARIAVEL EX: NÃO PODE USAR ASPAS DUPLAS  ----EX: LINHA DE BAIXO
    ----->  CONST MORANDO = 10
    CONSOLE.LOG (MORANDO)
    RESULTADO DA VARIAVEL VAI SER BUSCADO NO LOG MORANGO, VALOR DO = A 10
*/
let numeroDeAlunosDasalaSete = "69"